### ISSUE TITLE
[discussion] How to support auto scaling for Ray cluster

### ISSUE THREAD

**Issue by gaocegege** [ray-project/ray-operator#7]
We should investigate if we could use HPA. Here are some discussions about the topic:

From Eric Liang

> One question is whether we can protect certain pods from removal with HPA. For example, those with running actors on them should not be removed. I'm looking through the documentation and there doesn't seem to be a way to do this.

From @silveryfu 

> re. HPA pod protection at scale-down: scaling down is hard and interesting. The easier path is to have ray support readiness/liveness probes s.t. k8s controllers can learn whether a ray worker should be considered at scale-down. From the k8s side, readiness probe is also the easier path to implement insides hpa. 

> k8s pings the pod on a http endpoint defined in the pod spec and decides what to do, e.g., based on the returned http header. Readiness probe, following k8s’s terminology, should be the one considered here.

> Both liveness and readiness probes are currently used by kubelet and the endpoint won’t be exposed as a cluster ip.

> So the controllers will need to check whether the pod state is “Ready” or “NotReady” (or any other customized status, see comments below) to decide whether to consider scaling down. 

> ..and the way for ray workers to “report its williness to get scale down” is to update the header returned by the readiness probe. 

> Did a quick scan on hpa implementation -- adding a GetPodStatus in https://github.com/kubernetes/kubernetes/blob/a1f4c2ed21ea008c59934a9c6a06fac3da72f963/pkg/controller/podautoscaler/metrics/rest_metrics_client.go to be used for HPA should work.

> The other tricky part is that if the pod state is NotReady, then no traffic from the Service will be sent to the pod. Fortunately, k8s supports more pod status now — the readinessGates, which is a stable feature post 1.14 — it means we can set pod status exclusively for Ray workers, e.g., “ray-operator.io/live-actor=True”.

From @gaocegege

> Introduce some technical background. HPA implements scale down by changing the deployment.spec.replicas. Then deployment controller uses replicaset to delete the extra replicas. The replicaset controller uses a custom sort algorithm to sort the pods and decide which pods should be deleted. The algorithm is here: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/controller_utils.go#L741 It will delete unready pods first. If there is no unready pods, it will delete ready pods.

**Comment by gaocegege** [comment]
I will write a design proposal for this feature this week. There are two approaches in my mind: HPA + deployment + Readiness probe/gate; or pod-based solution.

**Comment by xieydd** [comment]
I always think deployment is not  flexiable.Like mpi-operator statefulset or deployment you mentioned.Looking forward to your proposal.

**Comment by gaocegege** [comment]
Since we have https://github.com/ray-project/ray/pull/5492, I think we can archieve the repository.

/cc @edoakes @richardliaw @liucimin
